'use client'
// components/BriefingCard.tsx

interface Props {
  briefing: any
  loading: boolean
}

export default function BriefingCard({ briefing, loading }: Props) {
  if (loading) return <BriefingSkeleton />

  if (!briefing) {
    return (
      <div style={{
        marginTop: 26, padding: '32px',
        border: '1px solid var(--b1)', borderRadius: 14,
        background: 'var(--card)', color: 'var(--t2)',
        fontSize: 12, textAlign: 'center',
      }}>
        AI briefing generates after the first pipeline run with 5+ signals.
      </div>
    )
  }

  const { content, context, meta } = briefing
  const sentColor = context?.sentimentLabel === 'positive' ? 'var(--green)'
    : context?.sentimentLabel === 'negative' ? 'var(--red)' : 'var(--t2)'

  return (
    <div style={{
      marginTop: 26,
      border: '1px solid var(--b1)', borderRadius: 14,
      overflow: 'hidden', background: 'var(--card)',
    }}>
      {/* Header bar */}
      <div style={{
        padding: '16px 24px',
        background: 'linear-gradient(90deg, rgba(225,6,0,.08), transparent)',
        borderBottom: '1px solid var(--b1)',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div className="pd" />
          <span style={{ fontFamily: 'var(--font-bebas)', fontSize: 18, letterSpacing: '.08em' }}>
            {content?.headline || 'F1 DAILY INTELLIGENCE BRIEFING'}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <span className="badge badge-gray">{context?.totalSignals ?? 0} SIGNALS</span>
          {(context?.breakingCount ?? 0) > 0 && (
            <span className="badge badge-red">{context.breakingCount} BREAKING</span>
          )}
          <span style={{
            fontSize: 9, letterSpacing: '.1em',
            padding: '2px 8px', borderRadius: 20,
            color: sentColor,
            background: context?.sentimentLabel === 'positive' ? 'rgba(74,222,128,.1)'
              : context?.sentimentLabel === 'negative' ? 'rgba(225,6,0,.1)'
              : 'rgba(255,255,255,.05)',
          }}>
            {context?.sentimentLabel?.toUpperCase()} SENTIMENT
          </span>
        </div>
      </div>

      {/* Body */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: 0,
      }}>
        {/* Left column */}
        <div style={{ padding: '24px', borderRight: '1px solid var(--b1)' }}>
          <BriefingSection
            label="OVERVIEW"
            text={content?.leadParagraph}
            accent="var(--red)"
          />
          <BriefingSection
            label="TOP STORY"
            text={content?.topStory}
            accent="var(--gold)"
          />
        </div>

        {/* Right column */}
        <div style={{ padding: '24px' }}>
          <BriefingSection
            label={`DRIVER SPOTLIGHT · ${context?.topDriver?.toUpperCase() || ''}`}
            text={content?.driverSpotlight}
            accent="var(--blue)"
          />
          {content?.controversyNote && (
            <BriefingSection
              label="⚠ CONTROVERSY WATCH"
              text={content.controversyNote}
              accent="var(--gold)"
            />
          )}
          <BriefingSection
            label="WHAT TO WATCH"
            text={content?.whatToWatch}
            accent="var(--green)"
          />
        </div>
      </div>

      {/* Footer */}
      <div style={{
        padding: '10px 24px',
        borderTop: '1px solid var(--b1)',
        display: 'flex', justifyContent: 'space-between',
        background: 'var(--bg2)',
        fontSize: 9, color: 'var(--t3)', letterSpacing: '.1em',
      }}>
        <span>GENERATED BY {meta?.modelUsed?.toUpperCase() || 'LLAMA3-8B'} · SNOWFLAKE CORTEX</span>
        <span>{meta?.generatedAt
          ? new Date(meta.generatedAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }) + ' UTC'
          : '--:--'
        }</span>
      </div>
    </div>
  )
}

function BriefingSection({ label, text, accent }: { label: string; text?: string; accent: string }) {
  if (!text) return null
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{
        fontSize: 9, letterSpacing: '.16em',
        color: accent, marginBottom: 8,
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <div style={{ width: 14, height: 1, background: accent }} />
        {label}
      </div>
      <p style={{ fontSize: 12, color: 'var(--t2)', lineHeight: 1.7 }}>{text}</p>
    </div>
  )
}

function BriefingSkeleton() {
  return (
    <div style={{
      marginTop: 26, border: '1px solid var(--b1)',
      borderRadius: 14, overflow: 'hidden',
    }}>
      <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--b1)', display: 'flex', gap: 10 }}>
        <div className="skeleton" style={{ height: 20, width: 300 }} />
        <div className="skeleton" style={{ height: 20, width: 80, marginLeft: 'auto' }} />
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', padding: 24, gap: 24 }}>
        {[0,1,2,3].map(i => (
          <div key={i}>
            <div className="skeleton" style={{ height: 10, width: 100, marginBottom: 8 }} />
            <div className="skeleton" style={{ height: 60, width: '100%' }} />
          </div>
        ))}
      </div>
    </div>
  )
}
